heredoc
TR-42/minishell pull request #17
Opened 2023-05-21 06:19 UTC by TetsuOtter

heredoc機能を実装しました。
本当は文字列の読み込みについてreadlineを使ってやるべきではあるんですが、とりあえずgnlを使って実装しています。

## 処理の流れ

1. (入力 -> Tokenize/Validation)
2. CMDTYP_RED_HEREDOCなものをチェック
3. `$TMPDIR/minish_heredoc_*`なファイルを新規作成 (`_0`から順に作成済みかチェックし、最大で10桁までトライする)
4. gnlを用いて1行ずつ読み込み、そしてdelimiterでない場合はそのファイルに書き込む
5. forkで子プロセスを立ち上げる
6. (子プロセス) 先ほどのファイルを開き、そのfdを`fd_to_this`にセットする
7. (子プロセス) dup2等、パイプと同じフローを辿る
8. (親プロセス) waitpidで子プロセスの終了を待つ
9. (親プロセス) tmpファイルを削除

![image](https://github.com/TR-42/minishell/assets/31824852/eaaab156-abd1-4994-9f0c-d474a7471c63)

## 仕様 (注意事項)

- `cat << $ABC`等と入力した場合、delimiterは`$ABC`という文字列になります。変数ABCの中身は展開されません
- `$TMPDIR`が存在しない場合、`/tmp`に作成を試行します。
- tmpファイルの作成に失敗した場合、コマンドは実行されません。
- `cat << ''`等と入力した場合、空文字列 = 空行がdelimiterになります。

---

今回の変更範囲は 49ee2ab92d7b62f86b90593ca9bfb0193b383362...10e674d072e63b35195fc5e28b6bb2f524ab82f3 だけです。
これ以前のものは #11 に含まれています。

2023-05-22 08:43 UTC, paphio-kitsuki requested changes
tmpファイルでのやり取り、さすがです！
gnlだと確かにBackSpaceが読み取れませんからね...
readlineだと改行無しの一行( & 要 free )が返る点は注意してください！
それと、とても些細なミスですが、指摘した点の修正もお願いします。

2023-05-22 08:43 UTC, paphio-kitsuki commented on srcs/childs/_redirect.c
> +	else if (type == CMDTYP_RED_APPEND)
ここにはたどり着かないのでは？50行目の「APPEND」は「IN」ですかね？

2023-05-22 09:35 UTC, TetsuOtter commented on srcs/childs/_redirect.c
> +	else if (type == CMDTYP_RED_APPEND)
確かに…! ご指摘の通り、50行目は`APPEND`ではなく`IN`が正しいです。
後ほど修正をかけますね。ありがとうございます！

2023-05-23 01:05 UTC, paphio-kitsuki approved these changes
修正確認しました。あとは問題ないと思います！

2023-05-23 01:05 UTC, merged