make builtins
TR-42/minishell pull request #27
Opened 2023-05-22 03:08 UTC by paphio-kitsuki

ビルトインの土台部分を作成しました。
windows環境のため、挙動は確認していません。(VM使えば良いだけの話ですが、テスター作る気力が起きませんでした...)
また、エラーハンドリングも未実装です。

使い方：　渡された引数は、どの関数でもそのまま(strで)渡してください。echoのみ、オプションはboolで。

残りタスク：
・echo(cdやexitも？)においての環境変数の対応
・errnoの保管
・エラーハンドリング

2023-05-22 10:50 UTC, TetsuOtter requested changes
後出しで申し訳ないですが、以下の関数も追加して頂きたいです🙇

- `int exec_builtin(const char **argv, int *exit_status)`
  - argv: 変数展開が済まされた、普通のmainに渡されるargvと同じ文字列配列
  - exit_status: 前回実行したコマンドのexit statusへのポインタ
  - (returns): builtinを実行したかどうか
    - `1`: 実行成功
    - `0`: builtinじゃなかったために実行しなかった場合
    - `-1`: malloc失敗やexit等によりプログラムを終了する場合 (exit_statusは適切に設定願います)
  - エラーメッセージ出力は関数内でやって頂けると嬉しいです。

よろしくお願いします!

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/_environ.h
> +char	***get_environs(void);
headers/builtin.hでも宣言されているので、こちらでは削除してしまっても良いかなと思います。
変にプロトタイプ宣言が二つあるのは好ましくないかなと思いまして。

```suggestion
```

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/_util_commands.c
> +	if (dst == NULL || *dst == NULL)
`dst`が not NULL かつ `*dst`が NULL の場合に、`dst`がfreeされずリークになります。

通常時
```
[
	"abc",
	"def",
	NULL
]
```
として、リーク発生ケースが `[NULL]` ですね。

```suggestion
	if (dst == NULL)
```

`*dst`のNULLチェックは35行目のwhile文でも行なっているので、単に`*dst == NULL`を削除するだけで問題なく動作するかなと思います。

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/_environ_utils.c
> +bool	set_environs(char **src)
(命名は人それぞれですし、ここで言うべきでは無いのでしょうが)
`set_environs`関数が呼ばれるのは、おそらくアプリを初期化するときだけではないでしょうか?
でしたら、初期化 = initializeから取って`init_environs`でも良いかなと思ったんですが、いかがでしょう…?

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/_environ_utils.c
> +		size = ft_strlen(name);
`name`はconstなので、このstrlenは外に出しちゃいましょう

```suggestion
	size = ft_strlen(name);
	while (*env != NULL)
	{
```

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/echo.c
> +void	builtin_echo(bool is_option_n, char *arg)
この関数には、「変数の展開が全て終わった状態の」argvを渡そうかなと思います。
(なので、TODOに書かれている`handle envs`は不要になるかなと思います)

で、`-n`フラグの有無判定もここでやって頂いて、argv一つ一つ、スペース区切りで出力をお願いします。

なお、argvおよびそこのデータは呼び出し元でfreeします。

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/exit.c
> +#include <stdlib.h>
23行目で`errno`を参照しているので、`errno.h`のincludeをお願いします。

```suggestion
#include <errno.h>
#include "_environ.h"
#include "ft_is/ft_is.h"
#include "ft_string/ft_string.h"
#include <stdlib.h>
```

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/exit.c
> +	exit(status);
リーク対策の都合上、`exit`関数はmain関数あたりまで戻って実行させたいのですが、いかがでしょう…?

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/export.c
> +bool	builtin_export(char **args)
`export`を引数無しで実行すると、
```
...
declare -x USER=tetsu
declare -x HOME=/Users/tetsu
...
```
のような形で、環境変数を出力するようです。

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/exit.c
> +		status = errno;
exitコマンドに引数が与えられなかったときは、「前回のコマンド(コマンドパイプライン)のexit status」を返すようです。
なので、「前回のコマンドのexit status (が記録されたint型引数へのポインタ)」を引数で受け取る形にして頂けると嬉しいです。

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/unset.c
> +#include <stdio.h>
31行目の`STDERR_FILENO`はunistd.hに宣言されているので、includeの追加をお願いします。


```suggestion
#include "_environ.h"
#include "ft_printf/ft_printf.h"
#include <stdio.h>
#include <unistd.h>
```

2023-05-22 10:50 UTC, TetsuOtter commented on srcs/builtin/unset.c
> +	}
```suggestion
		}
		args ++;
	}
```

2023-05-23 01:12 UTC, paphio-kitsuki commented on srcs/builtin/_environ_utils.c
> +bool	set_environs(char **src)
initではない気がするんですよね...
実はこの関数は、初期化だけでなく、終了時にNULLを渡すことで、環境変数のfreeの役割も担っているのです。

2023-05-23 01:20 UTC, paphio-kitsuki commented on srcs/builtin/_util_commands.c
> +	if (dst == NULL || *dst == NULL)
いえ、この関数は、文字列配列(char **)のポインタを取る関数です。
元の変数にNULLを代入するためにこうしています。
そのため、*dst も NULL なのは本来ないべきです。
35行目のNULLチェックは、**dstです。(tmp = *dst で、whileの条件は *tmp != NULL のため)

2023-05-23 01:29 UTC, paphio-kitsuki commented on srcs/builtin/exit.c
> +	exit(status);
了解です。では、その際に`set_environs(NULL)`(多分`init_environs`になります)の実行もお願いします。
ちなみに、ビルトインのexitで戻らないのは大丈夫ですか？

2023-05-23 01:32 UTC, paphio-kitsuki commented on srcs/builtin/unset.c
> +#include <stdio.h>
unistd.hだったのですね。代わりにstdio.hをincludeしていたので、こちらを書き換えておきます。

2023-05-23 03:10 UTC, TetsuOtter commented on srcs/builtin/_environ_utils.c
> +bool	set_environs(char **src)
NULLセットの役割があるなら、確かに`set_environs`でも良さそうですね
(ただ、私なら、NULLセットは関数を分けて`dispose_environs`的な名前を付けちゃいます)

2023-05-23 03:14 UTC, TetsuOtter commented on srcs/builtin/exit.c
> +	exit(status);
「ビルトインのexitで戻らない = noreturn = ここでexitを実行する」ことになるかなと思いますが、そうすると呼び出し元でmallocしてた領域をfreeできないので、そこで「リークだ！」って言われないか不安で…
可能であれば、`status` (exit_status) をreturnで返す形にして頂けるとありがたいです。

2023-05-23 12:39 UTC, TetsuOtter commented on srcs/builtin/_util_commands.c
> +	if (dst == NULL || *dst == NULL)
三重ポインタを見落としてました… ありがとうございます！

2023-05-24 09:55 UTC, TetsuOtter commented
完全に忘れてましたが、`cd`の実行で環境変数`PWD`も変わる (変える必要がある) ようです。
http://x68000.q-e-d.net/~68user/unix/pickup?PWD

2023-05-28 09:44 UTC, paphio-kitsuki commented
完成しました。挙動の確認はしていません。

2023-05-28 10:08 UTC, TetsuOtter commented
```sh
cc -Wall -Wextra -Werror -MMD -MP -I ./headers -I ./libft -I/opt/homebrew/opt/readline/include -c -o obj/_environ_utils.o ./srcs/builtin/_environ_utils.c || exit 0
./srcs/builtin/_environ_utils.c:103:17: error: comparison of distinct pointer types ('char *' and 'char **') [-Werror,-Wcompare-distinct-pointer-types]
                if (*src_envs != target)
                    ~~~~~~~~~ ^  ~~~~~~
1 error generated.
cc -Wall -Wextra -Werror -MMD -MP -I ./headers -I ./libft -I/opt/homebrew/opt/readline/include -c -o obj/env.o ./srcs/builtin/env.c || exit 0
./srcs/builtin/env.c:16:10: fatal error: '_util_command.h' file not found
#include "_util_command.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
cc -Wall -Wextra -Werror -MMD -MP -I ./headers -I ./libft -I/opt/homebrew/opt/readline/include -c -o obj/exec_builtin.o ./srcs/builtin/exec_builtin.c || exit 0
./srcs/builtin/exec_builtin.c:28:26: error: too few arguments to function call, expected 3, have 2
        if (ft_strncmp(*argv, CD) == 0)
            ~~~~~~~~~~          ^
./libft/ft_string/ft_string.h:33:6: note: 'ft_strncmp' declared here
int             ft_strncmp(const char *s1, const char *s2, size_t n);
                ^
./srcs/builtin/exec_builtin.c:29:29: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                *exit_status = builtin_cd(argv);
                                          ^~~~
./srcs/builtin/_exec_builtin.h:16:23: note: passing argument to parameter 'argv' here
int     builtin_cd(char **argv);
                          ^
./srcs/builtin/exec_builtin.c:30:33: error: too few arguments to function call, expected 3, have 2
        else if (ft_strncmp(*argv, ECHO) == 0)
                 ~~~~~~~~~~            ^
./libft/ft_string/ft_string.h:33:6: note: 'ft_strncmp' declared here
int             ft_strncmp(const char *s1, const char *s2, size_t n);
                ^
./srcs/builtin/exec_builtin.c:31:31: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                *exit_status = builtin_echo(argv);
                                            ^~~~
./srcs/builtin/_exec_builtin.h:17:25: note: passing argument to parameter 'argv' here
int     builtin_echo(char **argv);
                            ^
./srcs/builtin/exec_builtin.c:32:32: error: too few arguments to function call, expected 3, have 2
        else if (ft_strncmp(*argv, ENV) == 0)
                 ~~~~~~~~~~           ^
./libft/ft_string/ft_string.h:33:6: note: 'ft_strncmp' declared here
int             ft_strncmp(const char *s1, const char *s2, size_t n);
                ^
./srcs/builtin/exec_builtin.c:33:30: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                *exit_status = builtin_env(argv);
                                           ^~~~
./srcs/builtin/_exec_builtin.h:18:24: note: passing argument to parameter 'argv' here
int     builtin_env(char **argv);
                           ^
./srcs/builtin/exec_builtin.c:34:33: error: too few arguments to function call, expected 3, have 2
        else if (ft_strncmp(*argv, EXIT) == 0)
                 ~~~~~~~~~~            ^
./libft/ft_string/ft_string.h:33:6: note: 'ft_strncmp' declared here
int             ft_strncmp(const char *s1, const char *s2, size_t n);
                ^
./srcs/builtin/exec_builtin.c:36:31: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                *exit_status = builtin_exit(argv, *exit_status);
                                            ^~~~
./srcs/builtin/_exec_builtin.h:19:25: note: passing argument to parameter 'argv' here
int     builtin_exit(char **argv, int status);
                            ^
./srcs/builtin/exec_builtin.c:39:35: error: too few arguments to function call, expected 3, have 2
        else if (ft_strncmp(*argv, EXPORT) == 0)
                 ~~~~~~~~~~              ^
./libft/ft_string/ft_string.h:33:6: note: 'ft_strncmp' declared here
int             ft_strncmp(const char *s1, const char *s2, size_t n);
                ^
./srcs/builtin/exec_builtin.c:40:33: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                *exit_status = builtin_export(argv);
                                              ^~~~
./srcs/builtin/_exec_builtin.h:20:27: note: passing argument to parameter 'argv' here
int     builtin_export(char **argv);
                              ^
./srcs/builtin/exec_builtin.c:41:32: error: too few arguments to function call, expected 3, have 2
        else if (ft_strncmp(*argv, PWD) == 0)
                 ~~~~~~~~~~           ^
./libft/ft_string/ft_string.h:33:6: note: 'ft_strncmp' declared here
int             ft_strncmp(const char *s1, const char *s2, size_t n);
                ^
./srcs/builtin/exec_builtin.c:42:30: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                *exit_status = builtin_pwd(argv);
                                           ^~~~
./srcs/builtin/_exec_builtin.h:21:24: note: passing argument to parameter 'argv' here
int     builtin_pwd(char **argv);
                           ^
./srcs/builtin/exec_builtin.c:43:34: error: too few arguments to function call, expected 3, have 2
        else if (ft_strncmp(*argv, UNSET) == 0)
                 ~~~~~~~~~~             ^
./libft/ft_string/ft_string.h:33:6: note: 'ft_strncmp' declared here
int             ft_strncmp(const char *s1, const char *s2, size_t n);
                ^
./srcs/builtin/exec_builtin.c:44:32: error: passing 'const char **' to parameter of type 'char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                *exit_status = builtin_unset(argv);
                                             ^~~~
./srcs/builtin/_exec_builtin.h:22:26: note: passing argument to parameter 'argv' here
int     builtin_unset(char **argv);
                             ^
14 errors generated.
cc -Wall -Wextra -Werror -MMD -MP -I ./headers -I ./libft -I/opt/homebrew/opt/readline/include -c -o obj/exit.o ./srcs/builtin/exit.c || exit 0
./srcs/builtin/exit.c:30:12: error: call to undeclared function 'print_error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        return (print_error(COMMAND, *argv, NOTNUMERR, 255));
                                ^
./srcs/builtin/exit.c:30:40: error: use of undeclared identifier 'NOTNUMERR'
                        return (print_error(COMMAND, *argv, NOTNUMERR, 255));
                                                            ^
2 errors generated.
cc -Wall -Wextra -Werror -MMD -MP -I ./headers -I ./libft -I/opt/homebrew/opt/readline/include -c -o obj/export.o ./srcs/builtin/export.c || exit 0
./srcs/builtin/export.c:15:10: fatal error: '_util_command.h' file not found
#include "_util_command.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
cc -Wall -Wextra -Werror -MMD -MP -I ./headers -I ./libft -I/opt/homebrew/opt/readline/include -c -o obj/ft_putstr_fd.o ./srcs/builtin/ft_putstr_fd.c || exit 0
./srcs/builtin/ft_putstr_fd.c:29:11: error: comparison of integers of different signs: 'ssize_t' (aka 'long') and 'size_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
                if (out != length)
                    ~~~ ^  ~~~~~~
1 error generated.
cc -Wall -Wextra -Werror -MMD -MP -I ./headers -I ./libft -I/opt/homebrew/opt/readline/include -c -o obj/pwd.o ./srcs/builtin/pwd.c | [...]

2023-05-28 11:16 UTC, TetsuOtter submitted a review, later dismissed

2023-05-28 11:17 UTC, TetsuOtter approved these changes

2023-05-28 11:17 UTC, merged