envpを生成する関数を作成した
TR-42/minishell pull request #49
Opened 2023-05-30 12:49 UTC by TetsuOtter

ついでに、二重配列のfree用の関数を作成しました。
また、builtinにて用意して頂いたenvを初期化/disposeするようにしました

2023-05-30 14:13 UTC, paphio-kitsuki requested changes
自分のMakefile編集も混ぜてくれたのですね、ありがとうございます！
initに失敗した際のエラー処理もしていただけると助かります。

また、 'exec_builtin' で、途中でenvの保存に失敗した際に、-1を返すように修正しておきますので、 'exec_builtin' で-1が帰ってきた後に 'get_environs' をしない限り、NULLが返ることはないかと思います。

2023-05-30 14:13 UTC, paphio-kitsuki commented on srcs/main.c
> +	init_environs(envp);
```suggestion
	if (!init_environs(envp))
		return (1);
```

2023-05-31 10:30 UTC, TetsuOtter commented on srcs/main.c
> +	init_environs(envp);
確かに、そこのエラーチェックは必要ですね。
エラーメッセージの出力付きで修正します。

2023-05-31 10:45 UTC, TetsuOtter commented on srcs/main.c
> +	init_environs(envp);
fixed with [661fc80](https://github.com/TR-42/minishell/pull/49/commits/661fc8004543602cd422798ab354367360fabb6b)

2023-06-03 10:59 UTC, paphio-kitsuki approved these changes

2023-06-03 10:59 UTC, merged