Builtin fix
TR-42/minishell pull request #87
Opened 2023-06-11 11:24 UTC by paphio-kitsuki

ビルトイン関係の様々なバグを修正しました。
コンパイル確認済み、挙動未確認。

close #66 #67 #70 #71 #83

2023-06-11 12:03 UTC, TetsuOtter commented
`export A+=...` をうまく実装できていなさそうです

```
minishell> export A+=a
minishell> export
declare -x A="a"
minishell> export A+=b
minishell> export     
declare -x A+="bb"
minishell> env
A+=bb
```

2023-06-11 12:34 UTC, TetsuOtter requested changes
- `export A+=...`が正常に動作していない
- `exit` だけで実行すると`too many arguments`
- `exit 1 2` でexitできてしまう
- 権限がない状態でpwdすると、`PWD=` が表示されてしまう

pwdについては、環境変数`PWD`が無い状態でも出力できると嬉しいです。
```
minishell> chmod 000 .
minishell> pwd
PWD=/Users/tetsu/ftgit/minishell/tmp
minishell> unset PWD
minishell> pwd
minishell: pwd: failure to execute this command
minishell> 
```

---

再現するかは任せますが、bashだとカレントディレクトリに権限が無くても、 `cd ..` や `cd ../` , `cd ..////` 等でも移動できるようです。
-> 絶対パスなら`chdir` に直接渡して、相対パスなら `pwd` とjoinさせる?

2023-06-11 12:39 UTC, TetsuOtter commented
Linuxでは、macOSと違ってカレントディレクトリに権限が無くても `getcwd` に成功してしまうようです。注意が必要ですね。

Linux環境でビルドできない問題に関して、export.cでの `‘SIZE_MAX’ undeclared` が原因のため、 export.cにて `#include <stdint.h>` を行うことでビルド可能になります。

2023-06-11 18:28 UTC, paphio-kitsuki commented
いつでもpwdを可能にするため、pwdを別で保管するようにしました。
権限なくとも移動できるよう、相対パスを絶対パスに変換する仕組みも実装しました。
ついでに、OLDPWDに戻る仕組みも実装しました。

2023-06-12 00:07 UTC, TetsuOtter commented on srcs/builtin/save_pwd.c
> +	tmp = search_environ("PWD");
`PWD` は変更されて渡される可能性もあるため、信じない方が良いかもしれません。

bashでも、PWDがセットされていても使用していないらしく、
```sh
minishell> bash
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
```
```sh
bash-3.2$ pwd
pwd: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
```
と出ます。
まぁこれは別のPRで対処しましょう。

---

ちなみに、`cd -` は普通に `OLDPWD` を参照してるみたいでした
```sh
bash-3.2$ echo $OLDPWD

bash-3.2$ cd -
bash: cd: OLDPWD not set
bash-3.2$ export OLDPWD=/
bash-3.2$ cd -
chdir: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
/
bash-3.2$ 
```sh

2023-06-12 00:11 UTC, TetsuOtter commented on srcs/builtin/exit.c
> +	if (get_strslen(argv) > 2)
bashでは `exit a 1` のような場合にexitしますが、まぁそこは独自仕様でも通せそうですね。

2023-06-12 00:16 UTC, TetsuOtter approved these changes

2023-06-12 00:16 UTC, merged

2023-06-12 02:29 UTC, paphio-kitsuki commented on srcs/builtin/exit.c
> +	if (get_strslen(argv) > 2)
そこが僕も疑問で、校舎Macではexitしなかった気もするんですよね…

2023-06-12 02:52 UTC, paphio-kitsuki commented on srcs/builtin/save_pwd.c
> +	tmp = search_environ("PWD");
むぐぐ…。
できるだけエラーを出さないよう、上手く保存されていないときのため、PWDを参照するようにしたのですが…。
うーん、PWDとは完全に切り離したほうが挙動が同じになりそうですね

2023-06-12 03:35 UTC, TetsuOtter commented on srcs/builtin/exit.c
> +	if (get_strslen(argv) > 2)
校舎Macでもexitしてましたね
exitしなかったのは、「最初の引数が有効である、複数の引数が渡されたexit」だけでした

2023-06-12 03:40 UTC, paphio-kitsuki commented on srcs/builtin/exit.c
> +	if (get_strslen(argv) > 2)
なるほど、そうでしたか！
では後ほど、こちらについても修正しておきます。